// ملف التقييم والمتابعة - روابط محقّقة (سبتمبر 2026)
// كل رابط تم التحقق من صلاحيته: تحميل مباشر، Google Docs، MediaFire أو رابط مختصر.

import type {EvaluationFile} from './types';

export const evaluationFiles: EvaluationFile[] = [
  {
    السنة: "الكل",
    العنوان: "الصفحة الجامعة: ملفات التقييم كل المستويات",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "https://instiressources.blogspot.com/2014/09/dossier-devaluation.html",
    نوع_الرابط: "page",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "صفحة تجمع أمثلة ملفات التقييم من س1 إلى س6",
  },
  {
    السنة: "1",
    العنوان: "ملف التقييم و المتابعة الدرجة الأولى",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://drive.google.com/uc?export=download&id=1ZyAXP7g3e0aIGHe_5zxjJ5Uqhg1brHvx",
    نوع_الرابط: "drive",
    متاح: true,
    سنة_النشر: "2025",
    ملاحظات: "تقييم عام لكل المواد - ملف PDF (1.9 مو)",
  },
  {
    السنة: "1",
    العنوان: "مثال لملف التقييم و المتابعة (dossier d'évaluation)",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "http://adf.ly/tcMmC",
    نوع_الرابط: "adfly",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "يتطلب المرور عبر رابط مختصر (إعلان)",
  },
  {
    السنة: "2",
    العنوان: "مثال لملف التقييم و المتابعة (dossier d'évaluation)",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "http://adf.ly/tcMrV",
    نوع_الرابط: "adfly",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "يتطلب المرور عبر رابط مختصر (إعلان)",
  },
  {
    السنة: "3",
    العنوان: "ملف التقييم في بداية السنة الدراسية (التقييم التوجيهي)",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/14or7ZwyhBj6Eim5r67Xs6ZE7SelOwKrn/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2025",
    ملاحظات: "التقييم التوجيهي في بداية السنة الدراسية",
  },
  {
    السنة: "3",
    العنوان: "Dossier d'évaluation 3ème année primaire",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://www.mediafire.com/file/f06qup180y475wq/dossier-d-%C3%A9valuation-3%C3%A8me-n3.doc-2128027395.doc",
    نوع_الرابط: "mediafire",
    متاح: true,
    سنة_النشر: "2019",
    ملاحظات: "",
  },
  {
    السنة: "3",
    العنوان: "كراس تقييم لغة فرنسية (3ème)",
    المادة: "الفرنسية",
    المصدر: "mawsouati.com",
    الرابط: "http://www.mediafire.com/file/uvi58s2uwf173w6/Dossier_d%2527%25C3%25A9valuation3_emeA_N3_.doc/file",
    نوع_الرابط: "mediafire",
    متاح: true,
    سنة_النشر: "2019",
    ملاحظات: "",
  },
  {
    السنة: "3",
    العنوان: "كراس تقييم بالفرنسية (3ème)",
    المادة: "الفرنسية",
    المصدر: "mawsouati.com",
    الرابط: "http://www.mediafire.com/file/qfb186w9th8ofiw/%25C3%25A9valuation_3%25C3%25A8me_ann%25C3%25A9e1.rar/file",
    نوع_الرابط: "mediafire",
    متاح: true,
    سنة_النشر: "2019",
    ملاحظات: "ملف مضغوط RAR",
  },
  {
    السنة: "3",
    العنوان: "Dossier d'évaluation 3ème n3",
    المادة: "الفرنسية",
    المصدر: "devoir.tn",
    الرابط: "https://www.devoir.tn/primaire/Doc/%D8%A7%D9%84%D8%B3%D9%803%D9%80%D9%86%D8%A9/%D9%88%D8%AB%D8%A7%D8%A6%D9%82-%D8%A7%D9%84%D9%85%D8%B9%D9%84%D9%85/%D9%88%D8%AB%D8%A7%D8%A6%D9%82-%D9%85%D8%AA%D9%86%D9%88%D8%B9%D8%A9-1/Fran%C3%A7ais/dossier-d-%C3%A9valuation-3%C3%A8me-n3.pdf",
    نوع_الرابط: "pdf",
    متاح: true,
    سنة_النشر: "2016",
    ملاحظات: "تحميل مباشر PDF (2 مو)",
  },
  {
    السنة: "3",
    العنوان: "Dossier d'évaluation 3ème n4",
    المادة: "الفرنسية",
    المصدر: "devoir.tn",
    الرابط: "https://www.devoir.tn/primaire/Doc/%D8%A7%D9%84%D8%B3%D9%803%D9%80%D9%86%D8%A9/%D9%88%D8%AB%D8%A7%D8%A6%D9%82-%D8%A7%D9%84%D9%85%D8%B9%D9%84%D9%85/%D9%88%D8%AB%D8%A7%D8%A6%D9%82-%D9%85%D8%AA%D9%86%D9%88%D8%B9%D8%A9-1/Fran%C3%A7ais/dossier-d-%C3%A9valuation-3%C3%A8me-n4.pdf",
    نوع_الرابط: "pdf",
    متاح: true,
    سنة_النشر: "2016",
    ملاحظات: "تحميل مباشر PDF (2.1 مو)",
  },
  {
    السنة: "3",
    العنوان: "ملف التقييم و المتابعة س3",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "http://adf.ly/sNagc",
    نوع_الرابط: "adfly",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "يتطلب المرور عبر رابط مختصر (إعلان)",
  },
  {
    السنة: "4",
    العنوان: "Dossier d'évaluation des prérequis (4ème)",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/1HeTVFA3iotHLQYVEmlJXLIHU_UGLyieB/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "تقييم المكتسبات في بداية السنة",
  },
  {
    السنة: "4",
    العنوان: "Dossier d'évaluation des pré-requis (4ème) - PDF",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/1MzKDfkp6Ybri7gCUJZ1nyLdH_YhO2iTh/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2025",
    ملاحظات: "نسخة PDF (0.1 مو)",
  },
  {
    السنة: "4",
    العنوان: "dossier d'évaluation de prérequi 4 ème année",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/177ZYd8Wjlm9BC8lV1x3IA0L6JEKA8yn5/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "",
  },
  {
    السنة: "4",
    العنوان: "Cahier d'évaluation 4ème année",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/1--_yE60AcEE7db23YiZ-IEHOXhrrGoU-/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "",
  },
  {
    السنة: "4",
    العنوان: "Cahier d'évaluation 4ème année - Français",
    المادة: "الفرنسية",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/1HbN_7NwQ-ERYvVd1jUbwpS5TWXFjUECA/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "",
  },
  {
    السنة: "4",
    العنوان: "Cahier d'évaluation 4ème année",
    المادة: "جميع المواد",
    المصدر: "devoir.tn",
    الرابط: "https://www.devoir.tn/primaire/Doc/%D8%A7%D9%84%D8%B3%D9%804%D9%80%D9%86%D8%A9/%D9%88%D8%AB%D8%A7%D8%A6%D9%82-%D8%A7%D9%84%D9%85%D8%B9%D9%84%D9%85/Parascolaires/Cahier%20d%E2%80%99%C3%A9valuation.pdf",
    نوع_الرابط: "pdf",
    متاح: true,
    سنة_النشر: "2016",
    ملاحظات: "تحميل مباشر PDF (1.1 مو)",
  },
  {
    السنة: "4",
    العنوان: "Dossier d'évaluation 4ème année",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "http://adf.ly/1OTzAU",
    نوع_الرابط: "adfly",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "يتطلب المرور عبر رابط مختصر (إعلان)",
  },
  {
    السنة: "4",
    العنوان: "Dossier d'évaluation 4ème année",
    المادة: "جميع المواد",
    المصدر: "eduscol.org",
    الرابط: "http://www.mediafire.com/download/6o3xhrfmyoojsd4/Dossier+d'%C3%A9valuation+-+4%C3%A8me+ann%C3%A9e+-.rar",
    نوع_الرابط: "mediafire",
    متاح: true,
    سنة_النشر: "2016",
    ملاحظات: "ملف مضغوط RAR من الحقيبة التعليمية س4",
  },
  {
    السنة: "5",
    العنوان: "Dossier d'évaluation 5ème année",
    المادة: "جميع المواد",
    المصدر: "mawsouati.com",
    الرابط: "https://drive.google.com/uc?export=download&id=1CvqCq23yVmaHbd3Q3EtimQfOn-ZR8u3Z",
    نوع_الرابط: "drive",
    متاح: true,
    سنة_النشر: "2022",
    ملاحظات: "ملف PDF (594 ك)",
  },
  {
    السنة: "5",
    العنوان: "ملف التقييم و المتابعة مجال العلوم والتنشئة (5ème)",
    المادة: "العلوم",
    المصدر: "mawsouati.com",
    الرابط: "https://drive.google.com/drive/folders/1HEgM9aK5SEaOdIpQK8emJ_meH5n9lGFd",
    نوع_الرابط: "drive_folder",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "مجلد Google Drive يحتوي على عدة وثائق",
  },
  {
    السنة: "5",
    العنوان: "ملف التقييم لغة فرنسية (5ème)",
    المادة: "الفرنسية",
    المصدر: "mawsouati.com",
    الرابط: "http://www.mediafire.com/file/rv5vq43f1s344ty/cahier_d%2527%25C3%25A9valuation_5eme.pdf/file",
    نوع_الرابط: "mediafire",
    متاح: true,
    سنة_النشر: "2024",
    ملاحظات: "",
  },
  {
    السنة: "5",
    العنوان: "دفتر التقييم و المتابعة مجال العلوم والتكنولوجيا (5ème)",
    المادة: "العلوم",
    المصدر: "mawsouati.com",
    الرابط: "https://docs.google.com/document/d/15yrDaqH5LpRIqSdsJS45Yg4JQtImBhaI/edit",
    نوع_الرابط: "docs",
    متاح: true,
    سنة_النشر: "2025",
    ملاحظات: "",
  },
  {
    السنة: "5",
    العنوان: "Cahier d'évaluation 5ème année",
    المادة: "جميع المواد",
    المصدر: "9raya.tn",
    الرابط: "https://9raya.tn/wp-content/uploads/2019/09/FB_IMG_1567681433589.pdf",
    نوع_الرابط: "pdf",
    متاح: true,
    سنة_النشر: "2019",
    ملاحظات: "تحميل مباشر PDF (715 ك)",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - énoncés 1er trimestre",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Enonces-des-performances-attendues1ere.doc",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - énoncés 2e trimestre",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Enonces-des-performances-attendues2trim.doc",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - énoncés 3e trimestre",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Enonces-des-performances-attendues3trim.doc",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - EVAL DE L'ÉCRIT n°1",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/EVAL-DE-L4ECRIT-N%C2%B0-1.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - évaluation modules 1-2",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Evaluation-au-terme-des-modules-1-et-2.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - évaluation modules 3-4",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Evaluation-au-terme-des-modules-3-et-4.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - évaluation modules 5-6",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/Evaluation-au-terme-des-modules-5-et-6.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - évaluation des prérequis",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/evaluation-des-prerequis.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "تقييم المكتسبات القبلية",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - façade",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/wp-content/uploads/2023/09/facade.docx",
    نوع_الرابط: "word",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "غلاف ملف التقييم",
  },
  {
    السنة: "6",
    العنوان: "Cahier d'évaluation 6ème (فرنسية) - vue d'ensemble",
    المادة: "الفرنسية",
    المصدر: "najahni.tn",
    الرابط: "https://www.najahni.tn/6eme-annee-francais-cahier-devaluation/",
    نوع_الرابط: "page",
    متاح: true,
    سنة_النشر: "2023",
    ملاحظات: "صفحة جامعة لكل ملفات cahier d'évaluation 6ème",
  },
  {
    السنة: "6",
    العنوان: "Dossier d'évaluation 6ème année",
    المادة: "جميع المواد",
    المصدر: "instiressources",
    الرابط: "http://adf.ly/sgp4n",
    نوع_الرابط: "adfly",
    متاح: true,
    سنة_النشر: "2014",
    ملاحظات: "يتطلب المرور عبر رابط مختصر (إعلان)",
  },
];

